# Generated by Django 5.0.6 on 2024-07-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bencana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wilayah", models.CharField(max_length=250)),
                ("total_bencana", models.CharField(max_length=10)),
                ("korban_luka", models.CharField(max_length=100)),
                ("korban_jiwa", models.CharField(max_length=50)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tbbencana",
            },
        ),
    ]
