# Generated by Django 5.0.6 on 2024-07-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bencana",
            name="korban_jiwa",
            field=models.IntegerField(),
        ),
    ]
