# Generated by Django 5.0.6 on 2024-07-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_bencana_korban_jiwa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bencana",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
